-- =====================================================================
-- V1__shopping_baseline.sql  (P1)
--
-- Shopping 은 "무엇을 파는가" (상품 기본정보·대표 이미지) 만 소유한다.
-- 가격·재고·판매 상태는 commerce-service 의 sales_info 가 product_id 로 참조한다.
-- 시간 컬럼은 모두 TIMESTAMP WITH TIME ZONE (Java Instant, UTC 저장).
-- =====================================================================


-- ----- product_image -------------------------------------------------
-- 업로드된 이미지 파일 1개. 파일 자체는 ImageStorage(로컬 폴더, 추후 S3)에 있고
-- 여기에는 서버가 생성한 storage_key 만 둔다. URL·파일 경로는 저장하지 않는다
-- (저장소를 바꿔도 데이터 이관이 필요 없도록 URL 은 조회 시점에 만든다).
-- original_filename: 업로드한 사람이 준 파일명. 표시용일 뿐 저장 위치에 쓰지 않는다.
CREATE TABLE product_image (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    storage_key       VARCHAR(128) NOT NULL,
    content_type      VARCHAR(64)  NOT NULL,
    size_bytes        BIGINT       NOT NULL,
    width             INTEGER      NOT NULL,
    height            INTEGER      NOT NULL,
    original_filename VARCHAR(255),
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_product_image_storage_key UNIQUE (storage_key),
    CONSTRAINT ck_product_image_size_positive CHECK (size_bytes > 0),
    CONSTRAINT ck_product_image_dimension_positive CHECK (width > 0 AND height > 0)
);


-- ----- product -------------------------------------------------------
-- 상품 기본정보. 판매정보 등록 전까지는 공개·주문 대상이 아니다 (판정은 commerce).
-- main_image_id   : 대표 이미지. NOT NULL 이라 이미지 없는 상품은 만들 수 없다.
--                   교체는 이미 저장된 새 이미지로 이 값만 바꾼다 (실패 시 기존 유지).
-- idempotency_key : 등록 재전송 중복 방지용 클라이언트 키 (헤더 X-Idempotency-Key).
-- version         : 기본정보 수정의 낙관적 락. 다른 수정이 먼저 반영되면 409.
CREATE TABLE product (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100)  NOT NULL,
    description     VARCHAR(2000) NOT NULL,
    main_image_id   BIGINT        NOT NULL,
    idempotency_key VARCHAR(64),
    version         BIGINT        NOT NULL DEFAULT 0,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_product_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT fk_product_main_image
        FOREIGN KEY (main_image_id) REFERENCES product_image (id)
);

-- 공개 목록의 최신 등록순 커서 조회 ((created_at, id) < (:cursorAt, :cursorId)).
CREATE INDEX ix_product_created_at_id ON product (created_at DESC, id DESC);

-- 이미지 교체·조회 시 이미지 기준 역참조.
CREATE INDEX ix_product_main_image_id ON product (main_image_id);
