-- =====================================================================
-- V1__commerce_baseline.sql  (Sprint 2 · P1)
--
-- 재고·주문·결제의 상태 전이는 Java `if` 가 아니라 SQL WHERE 조건으로
-- 안전 보장한다. 예시:
--   UPDATE sales_stock
--      SET available = available - :qty, reserved = reserved + :qty
--    WHERE sales_info_id = :id AND available >= :qty;
-- 낙관적 락(version 컬럼)은 SalesInfo.price 처럼 경쟁이 적은 필드에만.
-- 시간 컬럼은 모두 TIMESTAMP WITH TIME ZONE (Java Instant, UTC 저장).
-- =====================================================================


-- ----- sales_info ----------------------------------------------------
-- Shopping 서비스의 상품 하나에 대한 판매 조건 (가격·상태).
-- 상품 1개 = 판매정보 1개. product_id 로 Shopping 을 참조한다 (FK 아님).
CREATE TABLE sales_info (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id    BIGINT      NOT NULL,
    price         BIGINT      NOT NULL,
    status        VARCHAR(32) NOT NULL,
    version       BIGINT      NOT NULL DEFAULT 0,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_sales_info_product_id UNIQUE (product_id),
    CONSTRAINT ck_sales_info_price_positive CHECK (price > 0),
    CONSTRAINT ck_sales_info_status CHECK (
        status IN ('READY', 'ON_SALE', 'SOLD_OUT', 'PRIVATE')
    )
);


-- ----- sales_stock ---------------------------------------------------
-- 판매 재고. sales_info 1:1.
-- available: 아직 팔 수 있는 수량 (조회·주문 대상)
-- reserved : 이미 주문에 배정되어 결제 대기 중인 수량
-- 관리자 재고 추가는 available 만 늘린다. 결제 성공 시 reserved 를 소진,
-- 결제 실패/취소/만료 시 reserved -> available 복원. 모든 변경은 조건부 UPDATE 로.
CREATE TABLE sales_stock (
    sales_info_id BIGINT  NOT NULL PRIMARY KEY,
    available     INTEGER NOT NULL DEFAULT 0,
    reserved      INTEGER NOT NULL DEFAULT 0,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_sales_stock_sales_info
        FOREIGN KEY (sales_info_id) REFERENCES sales_info (id),
    CONSTRAINT ck_sales_stock_available_nonneg CHECK (available >= 0),
    CONSTRAINT ck_sales_stock_reserved_nonneg  CHECK (reserved  >= 0)
);


-- ----- orders --------------------------------------------------------
-- 주문. P1 은 단건 상품 주문이라 order_items 테이블을 두지 않는다 (P2 확장 시 도입).
-- order_number     : 외부에 노출되는 조회용 식별자 (예: OD-20260920-000123)
-- lookup_password_hash : 비회원 주문 조회용 비밀번호 bcrypt hash
-- product_name_snapshot: 주문 시점 상품명 (Shopping 상품명이 나중에 바뀌어도 유지)
-- idempotency_key  : 재전송 중복 주문 방지용 클라이언트 키 (헤더 X-Idempotency-Key)
-- expires_at       : 결제 없이 방치되면 만료될 시각. 만료 스케줄러가 조건부 UPDATE 대상
-- cancelled_at     : 결제 전 취소된 경우 기록. status='CANCELLED' 일 때만 NOT NULL
CREATE TABLE orders (
    id                    BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number          VARCHAR(64)  NOT NULL,
    sales_info_id         BIGINT       NOT NULL,
    quantity              INTEGER      NOT NULL,
    unit_price            BIGINT       NOT NULL,
    total_amount          BIGINT       NOT NULL,
    status                VARCHAR(32)  NOT NULL,
    buyer_name            VARCHAR(64)  NOT NULL,
    buyer_phone           VARCHAR(32)  NOT NULL,
    lookup_password_hash  VARCHAR(255) NOT NULL,
    product_name_snapshot VARCHAR(255) NOT NULL,
    idempotency_key       VARCHAR(64),
    expires_at            TIMESTAMP WITH TIME ZONE,
    cancelled_at          TIMESTAMP WITH TIME ZONE,
    version               BIGINT       NOT NULL DEFAULT 0,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_orders_order_number    UNIQUE (order_number),
    CONSTRAINT uk_orders_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT fk_orders_sales_info
        FOREIGN KEY (sales_info_id) REFERENCES sales_info (id),
    CONSTRAINT ck_orders_quantity_positive     CHECK (quantity > 0),
    CONSTRAINT ck_orders_unit_price_positive   CHECK (unit_price > 0),
    CONSTRAINT ck_orders_total_amount_positive CHECK (total_amount > 0),
    CONSTRAINT ck_orders_status CHECK (
        status IN (
            'PENDING_PAYMENT', 'PAYMENT_CONFIRMING',
            'PAID', 'FAILED', 'CANCELLED', 'EXPIRED'
        )
    )
);

-- 만료 스케줄러가 (status='PENDING_PAYMENT' AND expires_at < now()) 스캔에 사용.
-- H2 는 부분 인덱스 미지원이라 status 를 인덱스 앞에 두어 필터링 효율 확보.
CREATE INDEX ix_orders_status_expires_at ON orders (status, expires_at);

-- 판매 상태 변경·재고 조회에서 판매정보별 pending 주문 카운트에 사용.
CREATE INDEX ix_orders_sales_info_status ON orders (sales_info_id, status);


-- ----- payment_attempt -----------------------------------------------
-- Mock 결제 시도. 주문 1건에 대해 여러 시도가 남을 수 있다 (실패 후 재시도).
-- scenario             : 개발용 시나리오 지정 (INSTANT_SUCCESS 등). 결제 시작 시 고정.
-- scheduled_resolve_at : DELAYED_* 시나리오의 확정 예약 시각.
--                        In-process ScheduledExecutor 유실을 대비해
--                        PaymentDelayReconciler 가 이 컬럼으로 DB 스캔한다.
CREATE TABLE payment_attempt (
    id                   BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id             BIGINT      NOT NULL,
    scenario             VARCHAR(32) NOT NULL,
    status               VARCHAR(32) NOT NULL,
    requested_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    resolved_at          TIMESTAMP WITH TIME ZONE,
    scheduled_resolve_at TIMESTAMP WITH TIME ZONE,
    version              BIGINT      NOT NULL DEFAULT 0,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_payment_attempt_order
        FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT ck_payment_attempt_scenario CHECK (
        scenario IN (
            'INSTANT_SUCCESS', 'INSTANT_FAIL',
            'DELAYED_SUCCESS', 'DELAYED_FAIL'
        )
    ),
    CONSTRAINT ck_payment_attempt_status CHECK (
        status IN ('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', 'TIMEOUT')
    )
);

-- 주문 단위 결제 이력 조회.
CREATE INDEX ix_payment_attempt_order_id ON payment_attempt (order_id);

-- PaymentDelayReconciler 가 (status='PROCESSING' AND scheduled_resolve_at < now())
-- 스캔할 때 사용. H2 부분 인덱스 미지원이라 status 를 앞에 둔다.
CREATE INDEX ix_payment_attempt_status_scheduled
    ON payment_attempt (status, scheduled_resolve_at);
