-- Apply with the old Commerce instances stopped: global idempotency becomes member-scoped.
ALTER TABLE orders ADD COLUMN member_id VARCHAR(36);
ALTER TABLE orders ADD COLUMN source_cart_item_id BIGINT;
ALTER TABLE orders ADD COLUMN requested_total_amount BIGINT;
ALTER TABLE orders ALTER COLUMN lookup_password_hash DROP NOT NULL;
ALTER TABLE orders DROP CONSTRAINT uk_orders_idempotency_key;
ALTER TABLE orders ADD CONSTRAINT uk_orders_member_idempotency UNIQUE (member_id, idempotency_key);
CREATE INDEX ix_orders_member_created ON orders (member_id, created_at DESC, id DESC);

CREATE TABLE cart_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id VARCHAR(36) NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_cart_member_product UNIQUE (member_id, product_id),
    CONSTRAINT ck_cart_quantity CHECK (quantity > 0),
    CONSTRAINT ck_cart_product CHECK (product_id > 0)
);
-- source_cart_item_id is an immutable replay identifier, not a FK: the item is deleted on purchase.
