-- Existing in-flight purchases require explicit reconciliation before rollout.
DO $$ BEGIN
 IF EXISTS (SELECT member_id FROM orders WHERE status IN ('PENDING_PAYMENT','PAYMENT_CONFIRMING') GROUP BY member_id HAVING COUNT(*) > 1) THEN
  RAISE EXCEPTION 'Multiple active orders per member: settle or cancel existing purchases before V4. No orders or inventory were changed.';
 END IF;
END $$;
CREATE TABLE member_purchase_guard (member_id VARCHAR(36) PRIMARY KEY);
CREATE TABLE payment_group (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 group_number VARCHAR(64) NOT NULL UNIQUE,
 member_id VARCHAR(36) NOT NULL,
 request_key VARCHAR(64) NOT NULL,
 fingerprint VARCHAR(64) NOT NULL,
 total_amount BIGINT NOT NULL CHECK(total_amount>0),
 status VARCHAR(32) NOT NULL CHECK(status IN ('PENDING_PAYMENT','PAYMENT_CONFIRMING','PAID','FAILED','CANCELLED','EXPIRED')),
 expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
 payment_id BIGINT,
 version BIGINT NOT NULL DEFAULT 0,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL,
 updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
 UNIQUE(member_id,request_key)
);

CREATE INDEX ix_payment_group_expiry ON payment_group(status,expires_at,id);
ALTER TABLE orders ADD COLUMN payment_group_id BIGINT REFERENCES payment_group(id);
ALTER TABLE orders ADD COLUMN source_cart_item_version BIGINT;
CREATE INDEX ix_orders_payment_group ON orders(payment_group_id);
ALTER TABLE payment_attempt ADD COLUMN payment_group_id BIGINT REFERENCES payment_group(id);
ALTER TABLE payment_attempt ADD COLUMN request_key VARCHAR(64);
CREATE UNIQUE INDEX uk_payment_attempt_group ON payment_attempt(payment_group_id);
CREATE TABLE mock_gateway_result (
 attempt_id BIGINT PRIMARY KEY,
 outcome VARCHAR(32) NOT NULL CHECK(outcome IN ('SUCCESS','FAILED','TIMEOUT')),
 authorized_at TIMESTAMP WITH TIME ZONE NOT NULL
);
INSERT INTO member_purchase_guard(member_id) SELECT DISTINCT member_id FROM orders;

-- Keep old single orders accessible through the new group APIs. Multiple active
-- orders per member must be resolved before applying the active-member index.
INSERT INTO payment_group(group_number,member_id,request_key,fingerprint,total_amount,status,expires_at,payment_id,created_at,updated_at)
 SELECT 'PG-LEGACY-' || o.id,o.member_id,'legacy-order-' || o.id,'legacy',o.total_amount,o.status,
 COALESCE(o.expires_at,o.created_at + INTERVAL '15 minutes'),
 (SELECT p.id FROM payment_attempt p WHERE p.order_id=o.id ORDER BY p.id DESC LIMIT 1),o.created_at,o.updated_at FROM orders o;
UPDATE orders SET payment_group_id=(SELECT g.id FROM payment_group g WHERE g.group_number='PG-LEGACY-' || orders.id);
UPDATE payment_attempt SET payment_group_id=(SELECT g.id FROM payment_group g WHERE g.payment_id=payment_attempt.id),request_key='legacy-payment-' || order_id WHERE EXISTS (SELECT 1 FROM payment_group g WHERE g.payment_id=payment_attempt.id);
CREATE UNIQUE INDEX uk_payment_group_active_member ON payment_group(member_id) WHERE status IN ('PENDING_PAYMENT','PAYMENT_CONFIRMING');
