CREATE TABLE refund_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_group_id BIGINT NOT NULL REFERENCES payment_group(id),
    member_id VARCHAR(36) NOT NULL,
    idempotency_key VARCHAR(64) NOT NULL,
    request_fingerprint VARCHAR(64) NOT NULL,
    refund_amount BIGINT NOT NULL CHECK (refund_amount >= 0),
    status VARCHAR(32) NOT NULL CHECK (status IN ('PROCESSING', 'UNKNOWN', 'SUCCESS', 'FAILED')),
    requested_at TIMESTAMP WITH TIME ZONE NOT NULL,
    resolved_at TIMESTAMP WITH TIME ZONE,
    result_detail VARCHAR(512),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_refund_request_member_key UNIQUE (member_id, idempotency_key)
);

CREATE INDEX ix_refund_request_group_requested
    ON refund_request (payment_group_id, requested_at DESC, id DESC);
CREATE INDEX ix_refund_request_member_requested
    ON refund_request (member_id, requested_at DESC, id DESC);

CREATE TABLE refund_target_order (
    refund_request_id BIGINT NOT NULL REFERENCES refund_request(id),
    order_id BIGINT NOT NULL REFERENCES orders(id),
    product_id_snapshot BIGINT NOT NULL,
    seller_id_snapshot VARCHAR(36),
    refund_amount BIGINT NOT NULL CHECK (refund_amount >= 0),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (refund_request_id, order_id)
);

CREATE INDEX ix_refund_target_order ON refund_target_order (order_id);
CREATE INDEX ix_refund_target_seller_request ON refund_target_order (seller_id_snapshot, refund_request_id);
