CREATE TABLE broadcast (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    request_key VARCHAR(128) NOT NULL UNIQUE,
    fingerprint VARCHAR(64) NOT NULL,
    title VARCHAR(100) NOT NULL,
    scheduled_at TIMESTAMP WITH TIME ZONE NOT NULL,
    channel_arn VARCHAR(255) NOT NULL,
    playback_url VARCHAR(2048) NOT NULL,
    status VARCHAR(16) NOT NULL CHECK (status IN ('PREPARING', 'LIVE', 'ENDED')),
    started_at TIMESTAMP WITH TIME ZONE,
    ended_at TIMESTAMP WITH TIME ZONE,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_broadcast_status ON broadcast(status);
CREATE INDEX idx_broadcast_created_at ON broadcast(created_at DESC);
