CREATE TABLE broadcast_product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    broadcast_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    sales_id BIGINT NOT NULL,
    position INTEGER NOT NULL,
    CONSTRAINT fk_broadcast_product_broadcast
        FOREIGN KEY (broadcast_id) REFERENCES broadcast(id),
    CONSTRAINT uk_broadcast_product UNIQUE (broadcast_id, product_id)
);

CREATE INDEX idx_broadcast_product_position ON broadcast_product(broadcast_id, position);
