CREATE TABLE broadcast_chat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    broadcast_id BIGINT NOT NULL,
    member_id UUID NOT NULL,
    display_name VARCHAR(80) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_broadcast_chat_broadcast
        FOREIGN KEY (broadcast_id) REFERENCES broadcast(id)
);

CREATE INDEX idx_broadcast_chat_recent ON broadcast_chat(broadcast_id, created_at DESC, id DESC);
